/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba2;
import prueba2.ListaProfesores;
import prueba2.Profesor;
import javax.swing.JOptionPane;
/**
 *
 * @author Evelyn
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ROTULO = new javax.swing.JLabel();
        jLcedula = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        jLNombres = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        Nombres = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        jLHorario = new javax.swing.JLabel();
        tiempoClompeto = new javax.swing.JTextField();
        jLcarrera = new javax.swing.JLabel();
        Carrera = new javax.swing.JTextField();
        jButtIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Horasclase = new javax.swing.JTextField();
        jLhorascomple = new javax.swing.JLabel();
        hComplementarias = new javax.swing.JTextField();
        ComBoxTIPOSProfesor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        medioT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tiempoPar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ROTULO.setFont(new java.awt.Font("Adobe Devanagari", 0, 24)); // NOI18N
        ROTULO.setText("Registro Docente");

        jLcedula.setText("Cédula");

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });

        jLNombres.setText("Nombres");

        Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombresActionPerformed(evt);
            }
        });

        jLApellido.setText("Apellido");

        jLHorario.setText("Tiempo Completo");

        tiempoClompeto.setEditable(false);
        tiempoClompeto.setEnabled(false);
        tiempoClompeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoClompetoActionPerformed(evt);
            }
        });

        jLcarrera.setText("Carrera");

        jButtIngresar.setText("Ingresar");
        jButtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtIngresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Horas clase");

        jLhorascomple.setText("Horas complementarias");

        ComBoxTIPOSProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiempo completo", "Medio Tiempo", "Tiempo Parcial" }));
        ComBoxTIPOSProfesor.setToolTipText("");
        ComBoxTIPOSProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBoxTIPOSProfesorActionPerformed(evt);
            }
        });

        jLabel2.setText("Medio Completo");

        medioT.setEditable(false);
        medioT.setEnabled(false);
        medioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioTActionPerformed(evt);
            }
        });

        jLabel3.setText("Tiempo parcial");

        tiempoPar.setEditable(false);
        tiempoPar.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ROTULO, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLcedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 740, Short.MAX_VALUE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtIngresar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLhorascomple, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(medioT, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(hComplementarias, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tiempoClompeto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Carrera, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Horasclase, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Apellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tiempoPar))))
                        .addGap(129, 129, 129)
                        .addComponent(ComBoxTIPOSProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ROTULO)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLcedula)
                        .addGap(29, 29, 29)
                        .addComponent(jLNombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComBoxTIPOSProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoClompeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(medioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tiempoPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcarrera))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Horasclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hComplementarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLhorascomple))
                .addGap(18, 18, 18)
                .addComponent(jButtIngresar)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresActionPerformed

    private void tiempoClompetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoClompetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoClompetoActionPerformed

    private void jButtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtIngresarActionPerformed
        ListaProfesores lista = new ListaProfesores();
        String nombres = Nombres.getText();
        String apellidos = Apellido.getText();
        int cedula = Integer.parseInt(Cedula.getText());
        String carrera = Carrera.getText();
        int tipo = Integer.parseInt(tiempoPar.getText());
        if (tipo == 0) {
            int horasClase = Integer.parseInt(Horasclase.getText());
            if (horasClase > 2 & horasClase < 17) {
                lista.agregar(new ProfesorTiempoCompleto(cedula, nombres, apellidos, horasClase, carrera));
            } else {
                JOptionPane.showMessageDialog(null, "El docente de tiempo completo debe impartir desde 3 horas hasta 16 horas clase", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (tipo == 1) {
            int horasClase = Integer.parseInt(Horasclase.getText());
            if (horasClase == 10) {
                lista.agregar(new ProfesorMedioTiempo(cedula, nombres, apellidos, horasClase, carrera));
            } else {
                JOptionPane.showMessageDialog(null, "El docente de medio tiempo debe impartir 10 horas clase", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (tipo == 2) {
            int horascom = Integer.parseInt(hComplementarias.getText());
            int horasClase = Integer.parseInt(Horasclase.getText());
            if ((horasClase > 1 & horasClase < 10) & horascom < 20) {
                lista.agregar(new ProfesorTiempoParcial(cedula, nombres, apellidos, horasClase, carrera, horascom));
            } else {
                JOptionPane.showMessageDialog(null, "El docente de tiempo parcial trabaja menos de 20 horas a la semana y debe impartir de 2 a 9 horas clase.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        ListaProfesores.grabar();
        Apellido.setText("");
        Carrera.setText("");
        Cedula.setText("");
        Nombres.setText("");
     
        Horasclase.setText("");
        hComplementarias.setText("");
        

    }//GEN-LAST:event_jButtIngresarActionPerformed

    private void ComBoxTIPOSProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBoxTIPOSProfesorActionPerformed
        if(((String)ComBoxTIPOSProfesor.getSelectedItem()).equalsIgnoreCase("Tiempo Completo")){
            tiempoClompeto.setEditable(true);
            tiempoClompeto.setEnabled(true);
            /////
            medioT.setEditable(false);
            medioT.setEnabled(false);
            /////
            tiempoPar.setEditable(false);
            tiempoPar.setEnabled(false);
        }if(((String)ComBoxTIPOSProfesor.getSelectedItem()).equalsIgnoreCase("Medio tiempo")){
            medioT.setEditable(true);
            medioT.setEnabled(true);
            ////
            tiempoClompeto.setEditable(false);
            tiempoClompeto.setEnabled(false);
            //
            tiempoPar.setEditable(false);
            tiempoPar.setEnabled(false);
        }if(((String)ComBoxTIPOSProfesor.getSelectedItem()).equalsIgnoreCase("Tiempo parcial")){
            tiempoPar.setEditable(true);
            tiempoPar.setEnabled(true);
            //
            tiempoClompeto.setEditable(false);
            tiempoClompeto.setEnabled(false);
            //
            medioT.setEditable(false);
            medioT.setEnabled(false);
        } 
    }//GEN-LAST:event_ComBoxTIPOSProfesorActionPerformed

    private void medioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medioTActionPerformed

    public void limpiar() {
        Cedula.setText("");
        Nombres.setText("");
        Apellido.setText("");
        Carrera.setText("");
        tiempoClompeto.setText("");
        hComplementarias.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Carrera;
    private javax.swing.JTextField Cedula;
    private javax.swing.JComboBox<String> ComBoxTIPOSProfesor;
    private javax.swing.JTextField Horasclase;
    private javax.swing.JTextField Nombres;
    private javax.swing.JLabel ROTULO;
    private javax.swing.JTextField hComplementarias;
    private javax.swing.JButton jButtIngresar;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLHorario;
    private javax.swing.JLabel jLNombres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLcarrera;
    private javax.swing.JLabel jLcedula;
    private javax.swing.JLabel jLhorascomple;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField medioT;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField tiempoClompeto;
    private javax.swing.JTextField tiempoPar;
    // End of variables declaration//GEN-END:variables
}
